name: checked_exceptions
description: An analyzer plugin adding support for checked exceptions to Dart.
version: 1.0.0
repository: https://github.com/abitofevrything/checked_exceptions
publish_to: none

environment:
  sdk: ^3.7.0-27.0.dev

dependencies:
  analyzer: ^6.11.0
  analyzer_plugin: ^0.11.3
  collection: ^1.19.1
  custom_lint_builder: ^0.6.10
  checked_exceptions_annotations:
    path: ../checked_exceptions_annotations
  yaml: ^3.1.2

dev_dependencies:
  lints: ^3.0.0
  path: ^1.9.1
  test: ^1.25.8
