name: checked_exceptions
description: An analyzer plugin adding support for checked exceptions to Dart.
version: 1.0.0
repository: https://github.com/abitofevrything/checked_exceptions

environment:
  sdk: ^3.0.0

dependencies:
  analyzer: ^6.4.1
  analyzer_plugin: ^0.11.3
  custom_lint_builder: ^0.6.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
